# Generated by Django 3.1.1 on 2020-09-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20200906_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='parameters',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='location',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Aggregation',
        ),
    ]
