# Generated by Django 3.1.1 on 2020-09-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_parameter__city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
        ),
    ]
