# Generated by Django 3.1.1 on 2020-09-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20200908_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='avg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
