# Generated by Django 3.1.1 on 2020-09-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_auto_20200908_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='values',
        ),
        migrations.AddField(
            model_name='city',
            name='aggregation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='ref',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
