# Generated by Django 3.1.1 on 2020-09-10 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_auto_20200909_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='aggregation',
        ),
        migrations.RemoveField(
            model_name='city',
            name='parameters',
        ),
        migrations.AlterField(
            model_name='city',
            name='ref',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregation', to='weather.city'),
        ),
    ]
