# Generated by Django 3.1.1 on 2020-09-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_auto_20200910_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='location',
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
        ),
    ]
