# Generated by Django 3.1.1 on 2020-09-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_auto_20200910_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='values',
            field=models.JSONField(default=list),
        ),
    ]
