# Generated by Django 3.1.1 on 2020-09-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0020_auto_20200911_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='_city',
            new_name='_location',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='values',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
