# Generated by Django 3.1.1 on 2020-09-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0021_auto_20200911_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
