# Generated by Django 3.1.1 on 2020-09-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0023_auto_20200915_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='values',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
