# Generated by Django 3.1.1 on 2020-09-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0028_parameter_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='aggregation',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
