# Generated by Django 3.1.1 on 2020-09-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0030_auto_20200916_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='aggregation',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
