# Generated by Django 3.1.1 on 2020-09-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0031_auto_20200916_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'locations'},
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='aggregation',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='values',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
