# Generated by Django 3.1.1 on 2020-09-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0032_auto_20200918_1002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together={('name', '_location')},
        ),
    ]
