# Generated by Django 3.1.1 on 2020-09-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0033_auto_20200918_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
